### ISSUE TITLE
Android - Error BIDDING: SDK class files not found for BIDDING

### ISSUE THREAD

**Issue by victorvhpg** [admost/AMR-CORDOVA-PLUGIN#6]
SDK class files not found for BIDDING : IRONSOURCE
 SDK class files not found for BIDDING : MOPUB 

Are there a new adapter for these SDK ?

**Comment by victorvhpg** [comment]
@admost  @sntahmaz  any help ?

**Comment by sntahmaz** [comment]
Hi @victorvhpg, 
Yes, these networks are also integrated with Admost. You should add related implementation lines. However, to use this plugin, you should be a customer of [Admost](https://www.admost.com/). If you are already our customer, please write to amr@kokteyl.com, and we will help you better.
